version: 2
jobs:
  build_zuk:
    docker:
      - image: ubuntu:latest
    working_directory: /root/build_zuk
    steps:
      - run: apt-get update
      - run: apt-get -y install git
      - run: git clone https://github.com/ajaivasudeve/kernel --depth=1 -b zuk .
      - run: bash build.sh

workflows:
  version: 2
  zuk_build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - zuk    
    jobs:
      - build_zuk
